# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\program_py\read_translate\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("实时翻译")
        Form.resize(558, 485)
        self.asr_text = QtWidgets.QLabel(Form)
        self.asr_text.setGeometry(QtCore.QRect(40, 40, 71, 31))
        self.asr_text.setObjectName("asr_text")
        self.translate_text = QtWidgets.QLabel(Form)
        self.translate_text.setGeometry(QtCore.QRect(40, 230, 72, 15))
        self.translate_text.setObjectName("translate_text")
        self.asr_ans = QtWidgets.QTextBrowser(Form)
        self.asr_ans.setGeometry(QtCore.QRect(140, 30, 256, 151))
        self.asr_ans.setObjectName("asr_ans")
        self.translate_ans = QtWidgets.QTextBrowser(Form)
        self.translate_ans.setGeometry(QtCore.QRect(140, 220, 256, 151))
        self.translate_ans.setObjectName("translate_ans")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(100, 420, 93, 28))
        self.start.setObjectName("start")
        self.display = QtWidgets.QPushButton(Form)
        self.display.setGeometry(QtCore.QRect(320, 420, 93, 28))
        self.display.setObjectName("display")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "实时翻译"))
        self.asr_text.setText(_translate("Form", "识别内容"))
        self.translate_text.setText(_translate("Form", "翻译内容"))
        self.start.setText(_translate("Form", "开始识别"))
        self.display.setText(_translate("Form", "关闭"))
